export async function handler() {
  return {
    statusCode: 200,
    body: /* html */ `
<html>
<head>
    <title>CDP Inject</title>
    <style>
        body {
            font-family: sans-serif;
        }
    </style>
    <head>
    <body>
        <h1>Hello Dynamic Page</h1>
        <p>This is a dynamic page generated by a function.</p>
        <p><a href="/">Static page</a></p>
    </body>
</html>
    `,
    headers: {
      'Content-Type': 'text/html',
    },
  }
}
